name: Main workflow
on:
  push:
    branches: [main]
jobs:
  job1:
    name: terraform-eks
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Provision VPC and EKS cluster
        run: cd main && ./1-deploy-infra.sh
      - name: Deploy apps
        run: cd main && ./2-deploy-apps.sh
      - name: Run Helm tests
        run: cd main && ./3-run-tests.sh
      - name: Run Puppeteer tests
        run: cd main && ./4-run-puppeteer-tests.sh
